In [81]:
import pandas as pd

In [417]:
import tarfile

tar_path = 'MovieSummaries.tar.gz'
extract_dir = './data'

with tarfile.open(tar_path, 'r') as tar:
    tar.extractall(path=extract_dir)

print(f'Files extracted to {extract_dir}')

Files extracted to ./data

In [82]:
data = pd.read_csv('./data/MovieSummaries/movie.metadata.tsv', sep='\t',header=None)
#Here if I don't do header=none, the first row becomes header, but it isn't
data.head()

,0,1,2,3,4,5,6,7,8
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science Fiction"", ""/m/03npn"": ""Horror"", ""/m/03k9fj"": ""Adventure"", ""/m/0fdjb"": ""Supernatural"", ""/m/02kdv5l"": ""Action"", ""/m/09zvmj"": ""Space western""}"
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0"": ""Drama"", ""/m/0hj3n01"": ""Crime Drama""}"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""Drama""}"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic thriller"", ""/m/09blyk"": ""Psychological thriller""}"
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [83]:
# It would be nice to change names of the columns, to know what we are working with
data.columns = ['wikipedia_id','freebase_id','name','release_date','revenue','runtime','languages','countries','genres']
data.head()

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science Fiction"", ""/m/03npn"": ""Horror"", ""/m/03k9fj"": ""Adventure"", ""/m/0fdjb"": ""Supernatural"", ""/m/02kdv5l"": ""Action"", ""/m/09zvmj"": ""Space western""}"
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0"": ""Drama"", ""/m/0hj3n01"": ""Crime Drama""}"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""Drama""}"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic thriller"", ""/m/09blyk"": ""Psychological thriller""}"
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [84]:
#I would like to see the whole text in genres column :)
pd.set_option('display.max_colwidth', 200)
data.head()

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science Fiction"", ""/m/03npn"": ""Horror"", ""/m/03k9fj"": ""Adventure"", ""/m/0fdjb"": ""Supernatural"", ""/m/02kdv5l"": ""Action"", ""/m/09zvmj"": ""Space western""}"
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0"": ""Drama"", ""/m/0hj3n01"": ""Crime Drama""}"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""Drama""}"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic thriller"", ""/m/09blyk"": ""Psychological thriller""}"
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [85]:
#So, in countries, languages and genres, the elements are formated as Freebase ID:name tuples
#We should filter these, so that we are left with just the info we need
import re

def extract_from_str(extract_str):
    extracted = re.findall(r'":\s*"([^"]+)"', extract_str) #regex for our case
    return ', '.join(extracted) 

data['genres'] = data['genres'].apply(extract_from_str)
data['countries'] = data['countries'].apply(extract_from_str)
data['languages'] = data['languages'].apply(extract_from_str)
data.head()

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,English Language,United States of America,"Thriller, Science Fiction, Horror, Adventure, Supernatural, Action, Space western"
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,English Language,United States of America,"Mystery, Biographical film, Drama, Crime Drama"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian Language,Norway,"Crime Fiction, Drama"
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English Language,United Kingdom,"Thriller, Erotic thriller, Psychological thriller"
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German Language,Germany,Drama

In [86]:
# We can now try to delve deeper into our data
# Are there any missing values?
import numpy as np

data.replace('', np.nan, inplace=True) #for columns that are strings, we check if there is an empty string
nan_count = data.isna().sum()
print(nan_count)

wikipedia_id        0
freebase_id         0
name                0
release_date     6902
revenue         73340
runtime         20450
languages       13866
countries        8154
genres           2294
dtype: int64

In [87]:
# Another thing that is problematic is the relase date-sometimes we do have a year, but not the exact date, which we want
exact_date = data['release_date'].str.match(r'^\d{4}-\d{2}-\d{2}$')
month_year = data['release_date'].str.match(r'^\d{4}-\d{2}$') # there are some movies who don't have the full exact date, but do have the month and year
year = data['release_date'].str.match(r'^\d{4}$')

print(f"Number of non valid dates: {data['release_date'].isna().sum()}")
print(f"Number of exact dates: {exact_date.sum()}")
print(f"Number of month-year dates: {month_year.sum()}")
print(f"Number of year dates: {year.sum()}")
print(f"Number of movies: {data.shape[0]}")

Number of non valid dates: 6902
Number of exact dates: 39373
Number of month-year dates: 3294
Number of year dates: 32172
Number of movies: 81741

In [88]:
# Quite a lot... We can try to get this information from some other dataset
# But how do we match movies from different datasets? Is the name enough?

duplicate_names = data['name'].value_counts()[data['name'].value_counts() > 1]

print("Number of duplicate movie names:", duplicate_names.shape[0])
print("Duplicate movie names and their counts:")
print(duplicate_names)

Number of duplicate movie names: 4387
Duplicate movie names and their counts:
name
Alice in Wonderland      17
Macbeth                  16
Les Misérables           13
A Christmas Carol        13
Hero                     12
                         ..
Perfect Day               2
Straw Dogs                2
Falling in Love Again     2
Aradhana                  2
Double Vision             2
Name: count, Length: 4387, dtype: int64

In [89]:
# Nope, there are actually some movies that have the same name, exactly 4387 of them
# The only other column, outside of ids, is the date, so we could check if there are movies that have both the same date as well as the same name
# Just in case, let's first check if there are any full on duplicates in dataset
duplicates = data[data.duplicated(keep=False)]
print(duplicates)

Empty DataFrame
Columns: [wikipedia_id, freebase_id, name, release_date, revenue, runtime, languages, countries, genres]
Index: []

In [90]:
# Cool! Now let's compare the dates too
duplicates_name_date = data[data.duplicated(subset=['name', 'release_date'], keep=False)]
duplicates_name_date.shape[0]

196

In [91]:
# 196 movies with same name and date, but how many of them actually have a date?
duplicates_name_date_no_nan = duplicates_name_date[duplicates_name_date['release_date'].notna()]
duplicates_name_date_no_nan.shape[0]

72

In [92]:
# Do some of the movies have the same name and year, but one has the exact date?
duplicates_names = data[data.duplicated(subset=['name'], keep=False)]
duplicates_names['release_date'] = pd.to_datetime(duplicates_names['release_date'], errors='coerce')
duplicates_names['release_year'] = duplicates_names['release_date'].dt.year
year_only = duplicates_names[duplicates_names['release_date'].dt.month.isna() & duplicates_names['release_date'].dt.day.isna()]
full_date = duplicates_names[~duplicates_names['release_date'].dt.month.isna() & ~duplicates_names['release_date'].dt.day.isna()]
merged_duplicates = pd.merge(year_only, full_date, on=['name', 'release_year'], suffixes=('_year_only', '_full_date'))

print(merged_duplicates[['name', 'release_year', 'release_date_year_only', 'release_date_full_date']])
# Okay at least this isn't happening

Empty DataFrame
Columns: [name, release_year, release_date_year_only, release_date_full_date]
Index: []

C:\Users\Marija\AppData\Local\Temp\ipykernel_10456\1469180076.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates_names['release_date'] = pd.to_datetime(duplicates_names['release_date'], errors='coerce')
C:\Users\Marija\AppData\Local\Temp\ipykernel_10456\1469180076.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates_names['release_year'] = duplicates_names['release_date'].dt.year

In [93]:
# Here is one example of a movie that has the same name and year, but there are two diffrent movies
data[data['name']=='Intermezzo']

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
69072,4599747,/m/0cbxys,Intermezzo,1939,NaN,70.0,English Language,United States of America,"Romantic drama, Romance Film, Drama, Black-and-white"
75375,7816833,/m/026f1dz,Intermezzo,1939,NaN,93.0,"Swedish Language, German Language",Sweden,"Romance Film, Drama, Black-and-white"

In [94]:
# How many of these movies have all the values?
duplicates_name_date_no_nan[duplicates_name_date_no_nan.notna().all(axis=1)]

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
16826,6061594,/m/0fn46x,Gossip,2000,12591270.0,90.0,"Italian Language, English Language",United States of America,"Thriller, Psychological thriller, Mystery, Drama, Suspense, Teen"
80080,3145964,/m/08vczx,"Yours, Mine and Ours",2005-11-23,72028752.0,88.0,English Language,United States of America,"Romance Film, Family Film, Comedy"

In [95]:
# Not many... Only 2
# What about the same name same genre?
duplicates_name_genre = data[data.duplicated(subset=['name', 'genres'], keep=False)]
duplicates_name_genre

,wikipedia_id,freebase_id,name,release_date,revenue,runtime,languages,countries,genres
273,28327554,/m/0cnxf8t,The Gamblers,1970,NaN,93.0,English Language,United States of America,Drama
392,22697314,/m/05zkfkf,Inherit the Wind,1999-05-29,NaN,113.0,English Language,United States of America,"Period piece, Courtroom Drama, Drama, Television movie"
640,32505827,/m/0h1cbks,Dost,NaN,NaN,NaN,Hindi Language,India,NaN
874,34129990,/m/0hr7b9d,Bella Donna,1915-11-15,NaN,NaN,"Silent film, English Language",NaN,Drama
1170,27744173,/m/0cc5j4y,The Long Haul,1988,NaN,113.0,Portuguese Language,Brazil,Drama
...,...,...,...,...,...,...,...,...,...
80898,7999199,/m/026m_h7,Desire,1936,NaN,95.0,"English Language, Spanish Language",United States of America,"Drama, Black-and-white"
80956,32998352,/m/0h536dw,A Daughter of Australia,1922,NaN,NaN,"Silent film, English Language",NaN,Silent film
81159,14373330,/m/03d1zb1,The Brothers Karamazov,1969-07-12,NaN,232.0,Russian Language,Soviet Union,Drama
81295,24162182,/m/07k8ww8,A Million Bid,1927-05-28,NaN,70.0,English Language,United States of America,"Silent film, Drama, Romance Film"
81319,26743619,/m/0bmj7yy,The Calendar,1931-10-31,NaN,80.0,English Language,United Kingdom,Drama

In [96]:
# So, it seems like combining name and date would be our best best to distinct movies

# To ensure uniqueness, we are going to delete all duplicates that have the same name and date
data_no_duplicates = data.drop_duplicates(subset=['name', 'release_date'], keep=False)

In [97]:
# Okay, now that we kind of got the feeling of what makes a movie unique, we should check if we have any other odd values in our dataset, aside from nan values
# Seems like the name can be pretty much everything
# Genre, countries, and languages could also be anything
# But revenue, if it is not nan, can't really be negative - we should check this 
data_no_duplicates[data_no_duplicates['revenue']<0]['revenue']

Series([], Name: revenue, dtype: float64)

In [98]:
# We will first try with dataset from kaggle: https://www.kaggle.com/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies?resource=download
'''
import zipfile
with zipfile.ZipFile('kaggle.zip', 'r') as zip_ref:
    zip_ref.extractall('./data/TMDB_movie/')
    '''

"\nimport zipfile\nwith zipfile.ZipFile('kaggle.zip', 'r') as zip_ref:\n    zip_ref.extractall('./data/TMDB_movie/')\n    "

In [138]:
data_kaggle = pd.read_csv('./data/TMDB_movie/TMDB_movie_dataset_v11.csv', sep=',')
data_kaggle.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,budget,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,160000000,https://www.warnerbros.com/movies/inception,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: ...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pictures","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, france, virtual reality, kidnapping, philosophy, spy, allegory, manipulation, car crash, heist, memory, architecture, los angeles, california, dream world,..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,165000000,http://www.interstellarmovie.net/,tt0816692,en,Interstellar,The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant to die here.,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Productions","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time, artificial intelligence (a.i.), nasa, time warp, dystopia, expedition, space travel, wormhole, famine, black hole, quantum mechanics, family relation..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,185000000,https://www.warnerbros.com/movies/dark-knight/,tt0468569,en,The Dark Knight,"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the s...",130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel Griffiths, Warner Bros. Pictures","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime fighter, superhero, anti hero, scarecrow, based on comic, vigilante, organized crime, tragic hero, anti villain, criminal mastermind, district attorney..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,237000000,https://www.avatar.com/movies/avatar,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, 20th Century Fox, Ingenious Media","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, space war, space colony, tribe, romance, alien, futuristic, space, alien planet, marine, soldier, battle, love affair, nature, anti war, power relatio..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,220000000,https://www.marvel.com/movies/the-avengers,tt0848228,en,The Avengers,"When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pu...",98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on comic, alien invasion, superhero team, aftercreditsstinger, duringcreditsstinger, marvel cinematic universe (mcu)"

In [139]:
data_kaggle[data_kaggle['revenue']!=0.0].shape[0]
# Oof, not a lot of them have revenues, but still, maybe this dataset does overlap with a lot of ours missing

20759

In [140]:
# What would mess up our work is if this dataset has duplicates, so we should check that
duplicates_kaggle = data_kaggle[data_kaggle.duplicated()]
duplicates_kaggle.shape[0]

368

In [141]:
# It does! We will drop these duplicates
data_kaggle_cleaned = data_kaggle.drop_duplicates()
print(f"Original shape: {data_kaggle.shape[0]}")
print(f"Shape after dropping: {data_kaggle_cleaned.shape[0]}")

Original shape: 1129227
Shape after dropping: 1128859

In [142]:
# Now we should check if there are any duplicates in the Kaggle dataset with the same name and date
#data_kaggle_cleaned['release_date'] = pd.to_datetime(data_kaggle_cleaned['release_date'], errors='coerce')
duplicates_kaggle_name_date = data_kaggle_cleaned[data_kaggle_cleaned.duplicated(subset=['title', 'release_date'], keep=False)]
duplicates_kaggle_name_date.shape[0]

21249

In [143]:
# In order to enrich our dataset, we have to make both datasets consistent so we are going to drop movies with the same name and date
data_kaggle_cleaned_no_duplicates = data_kaggle_cleaned.drop_duplicates(subset=['title', 'release_date'], keep=False, inplace=False)
data_kaggle_cleaned_no_duplicates.shape[0]

1107610

In [144]:
# So now we want to fill out the missing values in our dataset with the values from kaggle dataset but only for the movies that are in both datasets
# Merge the two datasets on the name and release year

# Here we are going to extract the year from the release date in both datasets
data_no_duplicates['release_year_merge'] = data_no_duplicates['release_date'].str.extract(r'(\d{4})')
data_kaggle_cleaned_no_duplicates['release_year_merge'] = data_kaggle_cleaned_no_duplicates['release_date'].str.extract(r'(\d{4})')

# Save duplicates for later
duplicates = data_no_duplicates[data_no_duplicates.duplicated(subset=['name', 'release_year_merge'], keep=False)]
data_no_duplicates = data_no_duplicates.drop_duplicates(subset=['name', 'release_year_merge'])
data_kaggle_cleaned_no_duplicates = data_kaggle_cleaned_no_duplicates.drop_duplicates(subset=['title', 'release_year_merge'])

# Merge the two datasets on the name and release year
merged_data = pd.merge(
    data_no_duplicates,
    data_kaggle_cleaned_no_duplicates,
    left_on=['name', 'release_year_merge'],
    right_on=['title', 'release_year_merge'],
    suffixes=('_wiki', '_kaggle'),
    how='left'
);
merged_data = merged_data.dropna(subset=['wikipedia_id'])
merged_data.head()

C:\Users\Marija\AppData\Local\Temp\ipykernel_10456\1967789076.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_kaggle_cleaned_no_duplicates['release_year_merge'] = data_kaggle_cleaned_no_duplicates['release_date'].str.extract(r'(\d{4})')

,wikipedia_id,freebase_id,name,release_date_wiki,revenue_wiki,runtime_wiki,languages,countries,genres_wiki,release_year_merge,id,title,vote_average,vote_count,status,release_date_kaggle,revenue_kaggle,runtime_kaggle,adult,backdrop_path,budget,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,tagline,genres_kaggle,production_companies,production_countries,spoken_languages,keywords
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,English Language,United States of America,"Thriller, Science Fiction, Horror, Adventure, Supernatural, Action, Space western",2001,10016.0,Ghosts of Mars,5.127,977.0,Released,2001-08-24,14010832.0,98.0,False,/anSbunnEMI0TSmizqUSRACoe18l.jpg,28000000.0,http://www.theofficialjohncarpenter.com/ghost-of-mars/,tt0228333,en,Ghosts of Mars,"In 2176, a Martian police unit is sent to pick up a highly dangerous criminal at a remote mining post. Upon arrival, the cops find the post deserted and something far more dangerous than any crimi...",14.189,/i2zztssCIbahGES1fdfWFmDXian.jpg,Terror is the same on any planet.,"Action, Horror, Science Fiction","Animationwerks, Screen Gems, Storm King Productions",United States of America,English,"future, planet mars, anti hero, possession, hot air balloon, mining, escaped convict, flashback, futuristic, zombie, train, survival horror, self mutilation, battering ram, ghost, cavern, ghost to..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,2000-02-16,NaN,95.0,English Language,United States of America,"Mystery, Biographical film, Drama, Crime Drama",2000,784579.0,Getting Away with Murder: The JonBenét Ramsey Mystery,0.000,0.0,Released,2000-02-16,0.0,60.0,False,NaN,0.0,NaN,tt0245916,en,Getting Away with Murder: The JonBenét Ramsey Mystery,"Dramatization of the story behind the murder of young JonBenet Ramsey. The program provides a concise view of the events surrounding the murder case, as pieced together by detectives and reporters...",0.600,NaN,NaN,"Drama, Crime",NaN,United States of America,English,"colorado, jonbenet"
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian Language,Norway,"Crime Fiction, Drama",1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English Language,United Kingdom,"Thriller, Erotic thriller, Psychological thriller",1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German Language,Germany,Drama,1983,11192.0,A Woman in Flames,5.300,13.0,Released,1983-05-11,0.0,106.0,False,/n12jS98GMLWSVaedpICrlAFsar6.jpg,0.0,NaN,tt0083949,de,Die flambierte Frau,"Eva, an upper-class housewife, frustratedly leaves her arrogant husband and decides to enter the call girl business. She lets Yvonne, a prostitute, teach her the basics and both set out for prey t...",2.801,/iKeCVR0x8vnRXLtjwjZ7EuVFlo7.jpg,NaN,Drama,Dieter Geissler Filmproduktion,Germany,German,"jealousy, eroticism, gigolo, longing, dominatrix, sadomasochism, conflict, divorce, bdsm"

In [145]:
# Now we are going to fill the missing values in the CMU dataset with the values from the kaggle dataset
merged_data['revenue'] = merged_data['revenue_wiki'].fillna(merged_data['revenue_kaggle'])
merged_data['revenue'] = merged_data['revenue'].replace(0, np.nan)
merged_data['runtime'] = merged_data['runtime_wiki'].fillna(merged_data['runtime_kaggle'])
merged_data['genres'] = merged_data['genres_wiki'].fillna(merged_data['genres_kaggle'])
merged_data['countries'] = merged_data['countries'].fillna(merged_data['production_countries'])
merged_data['languages'] = merged_data['languages'].fillna(merged_data['spoken_languages'])


# Now we want to enrich the release date column with days and months
merged_data['release_date'] = np.where(
    merged_data['release_date_kaggle'].str.match(r'^\d{4}-\d{2}-\d{2}$', na=False),
    merged_data['release_date_kaggle'],
    merged_data['release_date_wiki']
)
                      
merged_data['release_date'] = np.where(
    merged_data['release_date_kaggle'].str.match(r'^\d{4}-\d{2}$', na=False) & merged_data['release_date'].str.match(r'^\d{4}$', na=False), #check if wiki has only year
    merged_data['release_date_kaggle'],
    merged_data['release_date']
)

# We are going to drop the columns that we don't need anymore
merged_data.drop(columns=['revenue_wiki', 'revenue_kaggle', 'runtime_wiki', 'runtime_kaggle', 'genres_wiki', 'genres_kaggle', 'production_countries', 'spoken_languages', 
                          'keywords', 'id', 'title', 'vote_average', 'vote_count','status', 'release_date_kaggle', 'release_date_wiki', 'adult','backdrop_path','homepage','imdb_id',
                          'keywords','spoken_languages', 'tagline','production_companies','poster_path', 'original_language','original_title','overview','release_year_merge'], inplace=True)


# add duplicates back to the dataset
duplicates = duplicates.drop(columns=['release_year_merge']) # we don't want this column in our dataset
merged_data = pd.concat([merged_data, duplicates])
#show all the columns
pd.set_option('display.max_columns', None)

In [146]:
# What do we have now?
print("Null values in the merged dataset:")
print(merged_data.isna().sum())

Null values in the merged dataset:
wikipedia_id        0
freebase_id         0
name                0
languages        8856
countries        5796
budget          31532
popularity      31532
revenue         70454
runtime         11702
genres           1796
release_date     6778
dtype: int64

In [147]:
# Have we improved the dataset? Yes, we have filled some of the missing values
# We improved the revenue column with 2744 values
# Release date is improved by adding 21076 more full dates

# Count up the number of movies that have revenue data
print(f"Revenue values count: {merged_data['revenue'].notna().sum()}")

# Count up the number of movies that have full release date
print(f"Full release date count:{merged_data['release_date'].str.match(r'^\d{4}-\d{2}-\d{2}$').sum()}")

# Count up the number of movies that have only year as release date
print(f"Year only release date count:{merged_data['release_date'].str.match(r'^\d{4}$').sum()}")

#count the number of movies with only year and month as release date
print(f"Year and month release date count:{merged_data['release_date'].str.match(r'^\d{4}-\d{2}$').sum()}")

# Count up the number of movies that have missing release date
print(f"Missing release date count:{merged_data['release_date'].isna().sum()}")

Revenue values count: 11007
Full release date count:60335
Year only release date count:13241
Year and month release date count:1107
Missing release date count:6778

In [148]:
merged_data.head()

,wikipedia_id,freebase_id,name,languages,countries,budget,popularity,revenue,runtime,genres,release_date
0,975900,/m/03vyhn,Ghosts of Mars,English Language,United States of America,28000000.0,14.189,14010832.0,98.0,"Thriller, Science Fiction, Horror, Adventure, Supernatural, Action, Space western",2001-08-24
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey Mystery,English Language,United States of America,0.0,0.600,NaN,95.0,"Mystery, Biographical film, Drama, Crime Drama",2000-02-16
2,28463795,/m/0crgdbh,Brun bitter,Norwegian Language,Norway,NaN,NaN,NaN,83.0,"Crime Fiction, Drama",1988
3,9363483,/m/0285_cd,White Of The Eye,English Language,United Kingdom,NaN,NaN,NaN,110.0,"Thriller, Erotic thriller, Psychological thriller",1987
4,261236,/m/01mrr1,A Woman in Flames,German Language,Germany,0.0,2.801,NaN,106.0,Drama,1983-05-11

In [149]:
# Sooo now we have more resources for our analysis!
# Let's do a quick analysis for some problematic parts of our new dataset
# We see that budget can have both 0.0 and NaN - we should ensure that every entry has NaN if it doesn't have any meaningful value, just to be consistent
merged_data.loc[merged_data['budget'] == 0.0, 'budget'] = np.nan
merged_data.loc[merged_data['runtime'] == 0.0, 'runtime'] = np.nan #it doesn't make sense to have runtime 0.0

# Now let's check again non-nan values
print("Null values in the merged dataset:")
print(merged_data.isna().sum())

Null values in the merged dataset:
wikipedia_id        0
freebase_id         0
name                0
languages        8856
countries        5796
budget          73171
popularity      31532
revenue         70454
runtime         13644
genres           1796
release_date     6778
dtype: int64

In [150]:
# There might be a lot of genres - let's check
unique_genres = set()

for genre_list in merged_data['genres'].dropna():  # dropna to skip any NaN values
    genres = [genre.strip() for genre in genre_list.split(',')]
    unique_genres.update(genres)

print("Number of unique genres:", len(unique_genres))
print("Unique genres:", unique_genres)

Number of unique genres: 367
Unique genres: {'Family Film', 'Vampire movies', 'Demonic child', 'TV Movie', 'Interpersonal Relationships', 'Nature', 'Stoner film', 'Inventions & Innovations', 'Satire', 'Comedy horror', 'Extreme Sports', 'Romantic comedy', 'Graphic & Applied Arts', 'Christian film', 'Indian Western', 'Airplanes and airports', 'World History', 'Inspirational Drama', 'Comedy Thriller', 'Illnesses & Disabilities', 'Point of view shot', 'Western', 'Live action', 'Linguistics', 'Revenge', 'Comedy of manners', 'Silent film', 'Caper story', 'B-Western', 'Supermarionation', 'Haunted House Film', 'Alien Film', 'Heavenly Comedy', 'Political satire', 'Acid western', 'Sex comedy', 'Combat Films', 'Sexploitation', 'Business', 'Film', 'Sword and sorcery films', 'Juvenile Delinquency Film', 'Clay animation', 'Coming of age', 'Northern', 'Sci-Fi Horror', 'Tamil cinema', 'Czechoslovak New Wave', 'Crime Fiction', 'Zombie Film', 'Romance', 'Instrumental Music', 'Z movie', 'Chick flick', 'Slice of life story', 'Action Comedy', 'Experimental film', 'Animation', 'Filipino Movies', 'Political thriller', 'War', 'Musical Drama', 'Social problem film', 'Rockumentary', 'Remake', 'Docudrama', 'Heist', 'Adult', 'New Queer Cinema', 'Female buddy film', 'Roadshow theatrical release', 'Goat gland', 'Pre-Code', 'Monster', 'Alien invasion', 'Anti-war', 'Doomsday film', 'Humour', 'Future noir', 'Revisionist Fairy Tale', 'Media Studies', 'Fantasy', 'Kafkaesque', 'Black-and-white', 'Mystery', 'Animal Picture', 'Comedy of Errors', 'Americana', 'Anthropology', 'Animated cartoon', 'Suspense', 'Absurdism', 'Archaeology', 'Time travel', 'Pornographic movie', 'History', 'Jungle Film', 'Courtroom Drama', 'School story', 'Sword and Sandal', 'Period Horror', 'Crime Thriller', 'News', 'Bollywood', 'Epic', 'Musical comedy', 'Family Drama', 'Historical Epic', "Children's/Family", 'Natural disaster', 'Social issues', 'Animals', 'Action', 'Stand-up comedy', 'Biopic [feature]', 'Japanese Movies', 'World cinema', 'Epic Western', 'Detective', 'Courtroom Comedy', 'The Netherlands in World War II', 'Propaganda film', 'Biker Film', 'Auto racing', 'Travel', 'Film noir', 'Samurai cinema', 'Punk rock', 'Conspiracy fiction', 'Dystopia', 'Apocalyptic and post-apocalyptic fiction', 'Environmental Science', 'Crime Drama', 'Cyberpunk', 'Costume Adventure', 'Natural horror films', 'Mondo film', 'Prison film', 'Disaster', 'Cold War', 'Political drama', 'Gay pornography', 'Comedy-drama', 'Family', 'Fantasy Drama', 'New Hollywood', 'Private military company', 'Buddy cop', 'Sci Fi Pictures original films', 'Prison', 'Beach Party film', 'Childhood Drama', 'Creature Film', 'Backstage Musical', 'Comedy Western', 'Domestic Comedy', "Children's Issues", 'Sponsored film', 'Comedy film', 'Animated Musical', 'Documentary', 'Beach Film', 'Adventure', 'Sci-Fi Adventure', 'Film \\u00e0 clef', 'Erotic Drama', 'Adventure Comedy', 'Sci-Fi Thriller', 'Action Thrillers', 'Holiday Film', 'Women in prison films', 'Malayalam Cinema', 'Pinku eiga', 'Horse racing', 'Archives and records', 'Psycho-biddy', 'Escape Film', 'Operetta', 'Exploitation', 'Statutory rape', 'Space opera', 'Christmas movie', 'Slasher', 'Language & Literature', 'Law & Crime', 'Star vehicle', "Children's", 'Neorealism', 'Romance Film', 'Movie serial', 'Camp', 'Political Documetary', 'Historical fiction', 'Computers', 'Nuclear warfare', 'British New Wave', 'Werewolf fiction', 'Fan film', 'Fairy tale', 'Road-Horror', 'Health & Fitness', 'Short Film', 'Romantic drama', 'Comedy', 'Erotica', 'Gothic Film', 'Mythological Fantasy', 'Crime Comedy', 'Horror Comedy', 'Gross-out film', 'Biographical film', 'Historical drama', 'Romantic fantasy', 'Gay Interest', 'Biography', 'Coming-of-age film', 'Chinese Movies', 'Workplace Comedy', 'Period piece', 'Martial Arts Film', 'Tragedy', 'LGBT', 'Bengali Cinema', 'Religious Film', 'Tragicomedy', 'Cavalry Film', 'Road movie', 'Foreign legion', 'Jukebox musical', 'Bruceploitation', 'Anime', 'War effort', 'Ealing Comedies', 'Therimin music', 'Culture & Society', 'Hip hop movies', 'Romantic thriller', 'Roadshow/Carny', 'Psychological thriller', 'Stop motion', 'Sword and sorcery', 'Spaghetti Western', 'Concert film', 'Pornography', 'Silhouette animation', 'Race movie', 'Marriage Drama', 'Family & Personal Relationships', 'Libraries and librarians', 'Education', 'Family-Oriented Adventure', 'Softcore Porn', 'C-Movie', "Children's Entertainment", 'Media Satire', 'Anti-war film', 'Wuxia', "Children's Fantasy", 'Cult', 'Film-Opera', 'Baseball', 'Space western', 'Mockumentary', 'Costume Horror', 'Supernatural', 'Medical fiction', 'Gay', 'Kitchen sink realism', 'Historical Documentaries', 'Existentialism', 'Splatter film', 'Filipino', 'B-movie', 'Gay Themed', 'Superhero', 'Filmed Play', 'Screwball comedy', 'Outlaw biker film', 'Teen', 'Gulf War', 'Whodunit', 'Latino', 'Glamorized Spy Film', 'Journalism', 'Breakdance', 'Patriotic film', 'Film & Television History', 'Swashbuckler films', 'Blaxploitation', 'Expressionism', 'War film', 'Fantasy Comedy', 'Movies About Gladiators', 'Dance', 'Action/Adventure', 'Giallo', 'Ninja movie', 'Gender Issues', 'Fictional film', 'Detective fiction', 'Psychological horror', 'Neo-noir', 'Legal drama', 'Comdedy', 'Feminist Film', 'Boxing', 'Indie', 'Avant-garde', 'Homoeroticism', 'Outlaw', 'Black comedy', 'Parkour in popular culture', 'Early Black Cinema', 'Bloopers & Candid Camera', 'Prison escape', 'Gangster Film', 'Finance & Investing', 'Music', 'Sports', 'Anthology', 'Computer Animation', 'Horror', 'Melodrama', 'Science Fiction', 'Spy', 'Reboot', 'Feature film', 'Superhero movie', 'Thriller', 'Drama', 'Master Criminal Films', 'Television movie', 'Mumblecore', 'Slapstick', 'Science fiction Western', 'Costume drama', 'Tollywood', 'Hybrid Western', 'Steampunk', 'Chase Movie', 'Hardcore pornography', 'Musical', 'Ensemble Film', 'Educational', 'Crime', 'Albino bias', 'Film adaptation', 'Revisionist Western', 'Plague', 'Surrealism', 'Essay Film', 'Heaven-Can-Wait Fantasies', 'British Empire Film', 'Political cinema', 'Parody', 'Buddy Picture', 'Art film', 'Erotic thriller', 'Monster movie', 'Dogme 95', 'Hagiography', 'Buddy film', 'Singing cowboy', 'Tokusatsu', 'Gross out', 'Fantasy Adventure', 'Addiction Drama'}

In [153]:
# Too much... We should try to find a list of 20 (for example) representable genres, and sort our genres into these groups
genre_categories = {
    'Action': ['Action', 'Action/Adventure', 'Spy', 'Martial Arts Film', 'Superhero'],
    'Adventure': ['Adventure', 'Space opera', 'Swashbuckler films'],
    'Animation': ['Animation', 'Computer Animation', 'Anime', 'Clay animation', 'Stop motion'],
    'Comedy': ['Comedy', 'Comedy-drama', 'Black comedy', 'Slapstick', 'Romantic comedy'],
    'Crime': ['Crime', 'Gangster Film', 'Detective fiction', 'Heist', 'Crime Thriller'],
    'Documentary': ['Documentary', 'Docudrama', 'Rockumentary', 'Essay Film'],
    'Drama': ['Drama', 'Family Drama', 'Inspirational Drama', 'Biographical film', 'Tragedy'],
    'Family': ["Children's", 'Family', "Children's/Family", 'Family Film'],
    'Fantasy': ['Fantasy', 'Sword and sorcery', 'Fairy tale', 'Fantasy Adventure'],
    'Horror': ['Horror', 'Zombie Film', 'Slasher', 'Psychological horror', 'Monster'],
    'Musical': ['Musical', 'Operetta', 'Rockumentary', 'Backstage Musical', 'Jukebox musical'],
    'Mystery': ['Mystery', 'Whodunit', 'Suspense'],
    'Romance': ['Romance', 'Romantic comedy', 'Romantic drama', 'Romantic thriller', 'Chick flick'],
    'Science Fiction': ['Science Fiction', 'Sci-Fi Horror', 'Cyberpunk', 'Alien invasion', 'Time travel'],
    'Thriller': ['Thriller', 'Comedy Thriller', 'Psychological thriller', 'Action Thrillers'],
    'War': ['War', 'War film', 'Cold War', 'Anti-war'],
    'Western': ['Western', 'Spaghetti Western', 'Acid western', 'Epic Western'],
    'Historical': ['Historical', 'Historical Epic', 'Historical drama', 'Period piece'],
    'Superhero': ['Superhero', 'Superhero movie'],
    'Experimental': ['Experimental film', 'Avant-garde', 'Mockumentary', 'Absurdism']
}
def map_genres(genres_string):
    matched_genres = set()  
    
    if pd.notna(genres_string): 
        genres = [genre.strip() for genre in genres_string.split(',')]
        
        for genre in genres:
            for categories, options in genre_categories.items():
                if genre in options:
                    matched_genres.add(categories)
                    break  
    
    return ', '.join(matched_genres) if matched_genres else 'Other'

merged_data['genres'] = merged_data['genres'].apply(map_genres)
print(merged_data['genres'].value_counts())

genres
Drama                                                       16741
Other                                                       12053
Comedy                                                       8099
Documentary                                                  4743
Comedy, Drama                                                2657
                                                            ...
Romance, Thriller, Historical, Drama, Crime                     1
Family, Romance, Historical, Drama, Comedy                      1
Animation, Horror, Mystery, Science Fiction                     1
Action, Crime, Science Fiction, Drama                           1
Horror, Mystery, Science Fiction, Fantasy, Drama, Comedy        1
Name: count, Length: 1210, dtype: int64

In [156]:
# We do have roughly 12000 'Other' genres, but we are going to leave it like this for now, as it isn't that big of a number for this dataset
# We now want to save this dataset, as we are done for now!

file_path = '../data/movies_dataset.tsv'
merged_data.to_csv(file_path, sep='\t', index=False) # we are saving it as tsv, because originally it was in tsv format